/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerSettlementRouteImport } from './routes/customer-settlement'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentHistoryRouteImport } from './routes/payment-history'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesInvoicesRouteImport } from './routes/sales-invoices'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSettlementRoute = CustomerSettlementRouteImport.update({
  id: '/customer-settlement',
  path: '/customer-settlement',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentHistoryRoute = PaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesInvoicesRoute = SalesInvoicesRouteImport.update({
  id: '/sales-invoices',
  path: '/sales-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer-settlement': typeof CustomerSettlementRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/sales-invoices': typeof SalesInvoicesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer-settlement': typeof CustomerSettlementRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/sales-invoices': typeof SalesInvoicesRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer-settlement': typeof CustomerSettlementRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/payment-history': typeof PaymentHistoryRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/sales-invoices': typeof SalesInvoicesRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer-settlement'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/payment-history'
    | '/products'
    | '/reports'
    | '/sales-invoices'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer-settlement'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/payment-history'
    | '/products'
    | '/reports'
    | '/sales-invoices'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/customer-settlement'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/payment-history'
    | '/products'
    | '/reports'
    | '/sales-invoices'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerSettlementRoute: typeof CustomerSettlementRoute
  CustomersRoute: typeof CustomersRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  PaymentHistoryRoute: typeof PaymentHistoryRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  SalesInvoicesRoute: typeof SalesInvoicesRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-settlement': {
      id: '/customer-settlement'
      path: '/customer-settlement'
      fullPath: '/customer-settlement'
      preLoaderRoute: typeof CustomerSettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-history': {
      id: '/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof PaymentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-invoices': {
      id: '/sales-invoices'
      path: '/sales-invoices'
      fullPath: '/sales-invoices'
      preLoaderRoute: typeof SalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerSettlementRoute: CustomerSettlementRoute,
  CustomersRoute: CustomersRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  PaymentHistoryRoute: PaymentHistoryRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  SalesInvoicesRoute: SalesInvoicesRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
